### PR TITLE
Upgrade to latest version and change project names

### PR DESCRIPTION
**Pull request by rajadilipkolli**

### CODE REVIEW

**Comment by ttddyy** [comment]
@rajadilipkolli 

Thanks for keeping this project always upto date!!

Let me think about naming here. I'd like to make them consistent.
Probably all artifactIds to have `dsp-` prefix but sub module(directory) names to be not prefixed.

**Comment by rajadilipkolli** [comment]
When I import this as maven project then all modules which are imported are not grouped together. Only to group together I have changed submodule name to dsp.

Note:: I have many other projects in eclipse.

**Comment by rajadilipkolli** [comment]
Apologies for the misunderstanding from my side. Ur right, all artifact ids should be prepended with dsp- but subfolder names can remain the same.

**Comment by rajadilipkolli** [comment]
I have revert changes to the folder name.

**Comment by ttddyy** [comment]
@rajadilipkolli  Thanks, appreciate your changes!!

**Pull request merged**
