### PR TITLE
Upgrade to 1.5.6 and create datasource proxy to be inline with 2.0.0.M3

### PR DESCRIPTION
**Pull request by rajadilipkolli**
With spring 2.0.0.M3 creation of proxies is changed, to be in line with this change using AOP in lower versions too to create datasource proxy automatically.

With this change user can change to 2.0.0.M3+ version of spring boot

### CODE REVIEW

**Comment by ttddyy** [comment]
Thanks for keep updating these examples!!

I found this blog for how to configure datasource-proxy with spring boot 2.0.0.M3.
http://blog.arnoldgalovics.com/2017/06/26/configuring-a-datasource-proxy-in-spring-boot/

I'm just curious what are the changes for proxy creation in spring-boot 2.0.0.M3 ?
cc @galovics

**Comment by rajadilipkolli** [comment]
@ttddyy for details please see [here](https://gitter.im/spring-projects/spring-boot?at=5983602d2723db8d5e70a904)

**Comment by galovics** [comment]
There are no changes regarding proxy handling in the new boot version. My solution was a bit incorrect because when Spring was setting up the application context, I changed the bean type to the Proxy type instead of the type in the bean definition.

In this case, Spring expected some other type and that caused the issue. As you can see the new solution at the end of my article, I used CGLib to keep the original type hierarchy.

**Comment by galovics** [comment]
@rajadilipkolli could you please mention my article at least in the README if you've already included the code from it? Thanks!

**Comment by ttddyy** [comment]
Thanks for the details. 

@galovics
I had added a link to your blog post on the source code.

**Comment by rajadilipkolli** [comment]
@galovics, I should have done it in the first hand. I am sorry for that. Bean creation issue fix is from your blog post, but original post is from my struggle at https://stackoverflow.com/questions/44237787/how-to-use-user-defined-database-proxy-in-datajpatest

**Pull request merged**
